sudo: false
language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2

install:
  - composer install --prefer-dist

script:
  - composer cs
  - composer test

cache:
  directories:
    - $HOME/.composer/cache/files
